export const sellers = [
  {
    id: "seller-001",
    name: "A. Vance",
    initials: "AV",
    color: "#6B4EFF",
    memberSince: "2024-03",
    listingsCount: 4,
    responseTime: "< 2 hours",
    rating: 4.9,
    bio: "Experienced genre fiction author with 8 years of writing. Specializing in epic fantasy and dark romance."
  },
  {
    id: "seller-002",
    name: "M. Sterling",
    initials: "MS",
    color: "#E91E8C",
    memberSince: "2024-07",
    listingsCount: 2,
    responseTime: "< 4 hours",
    rating: 4.7,
    bio: "Former journalist turned fiction writer. Specializing in character-driven thrillers and literary fiction."
  },
  {
    id: "seller-003",
    name: "R. Holloway",
    initials: "RH",
    color: "#2D7A4F",
    memberSince: "2025-01",
    listingsCount: 3,
    responseTime: "< 6 hours",
    rating: 4.8,
    bio: "Business consultant and bestselling non-fiction author. Expert in productivity, leadership, and entrepreneurship."
  },
  {
    id: "seller-004",
    name: "J. Nakamura",
    initials: "JN",
    color: "#0097A7",
    memberSince: "2024-11",
    listingsCount: 2,
    responseTime: "< 3 hours",
    rating: 5.0,
    bio: "Sci-fi worldbuilder and tech writer. Hard science fiction with a focus on near-future scenarios."
  },
  {
    id: "seller-005",
    name: "C. Oduya",
    initials: "CO",
    color: "#E74C3C",
    memberSince: "2025-02",
    listingsCount: 1,
    responseTime: "< 8 hours",
    rating: 4.6,
    bio: "Debut thriller author with a background in criminal justice. Specializing in psychological suspense."
  }
];

export const categories = [
  { id: "fantasy",    label: "Fantasy",      count: 3, icon: "✦" },
  { id: "romance",    label: "Romance",      count: 2, icon: "♥" },
  { id: "thriller",   label: "Thriller",     count: 2, icon: "◈" },
  { id: "scifi",      label: "Sci-Fi",       count: 2, icon: "◉" },
  { id: "nonfiction", label: "Non-Fiction",  count: 2, icon: "◎" },
  { id: "children",   label: "Children's",   count: 1, icon: "★" },
  { id: "business",   label: "Business",     count: 1, icon: "◆" },
  { id: "mystery",    label: "Mystery",      count: 1, icon: "◇" },
];

export const listings = [
  {
    id: "rtp-001",
    title: "The Cartographer's Daughter",
    author: "A. Vance",
    sellerId: "seller-001",
    genre: "fantasy",
    audience: "adult",
    wordCount: 94200,
    price: 2400,
    negotiable: false,
    featured: true,
    packageType: "full",
    includes: ["Manuscript (.docx + .pdf)", "Cover design (.psd + .jpg)", "Chapter synopsis", "Series bible / Style guide"],
    formats: ["docx", "pdf", "psd"],
    description: "An epic standalone fantasy following Lyra, a young woman who discovers her deceased mother was secretly mapping the hidden territories between worlds. Armed with her mother's cryptic journals and an impossible compass, Lyra must traverse lands where geography is alive and borders shift with political power.\n\nThe story blends intricate worldbuilding with a deeply personal mystery at its core. The magic system is based on cartographic principles — those who understand maps can shape territory. The book has been fully developmental-edited and copyedited, query-ready with a polished synopsis and first-chapter hook.",
    excerpt: "The compass needle didn't point north. It pointed toward the blank space on every map Lyra had ever seen — the place her mother had spent fifteen years trying to reach, and had finally found the week she died.",
    listedDate: "2026-02-14",
    coverGradient: ["#1a1a2e", "#16213e", "#0f3460"],
    coverAccent: "#C9A84C",
    tags: ["magic system", "female protagonist", "standalone", "query-ready"],
    wordRange: "80k-100k"
  },
  {
    id: "rtp-002",
    title: "Every Shade of Ruin",
    author: "A. Vance",
    sellerId: "seller-001",
    genre: "romance",
    audience: "adult",
    wordCount: 82500,
    price: 1800,
    negotiable: true,
    featured: true,
    packageType: "cover",
    includes: ["Manuscript (.docx)", "Cover design (.jpg, print + digital versions)", "Blurb + tagline variants"],
    formats: ["docx", "jpg"],
    description: "A slow-burn contemporary romance between a disgraced architect and the preservation consultant hired to demolish his family's historic estate. Set against the backdrop of a crumbling Scottish manor and a tight deadline, the story weaves competing desires for renewal vs. legacy into a deeply emotional love story.\n\nFeatures dual POV, enemies-to-lovers arc, and a satisfying HEA. Cover art is custom-commissioned oil-painting style digital illustration. Fully polished, beta-read by five readers.",
    excerpt: "She had blueprints for every room except the one he kept locked. He told himself it was because it wasn't her business. He was three days into believing that.",
    listedDate: "2026-01-28",
    coverGradient: ["#1a0a15", "#3d1a2e", "#6b2d47"],
    coverAccent: "#E91E8C",
    tags: ["dual POV", "enemies to lovers", "HEA", "Scottish setting"],
    wordRange: "80k-100k"
  },
  {
    id: "rtp-003",
    title: "The Fold Protocol",
    author: "J. Nakamura",
    sellerId: "seller-004",
    genre: "scifi",
    audience: "adult",
    wordCount: 103000,
    price: 3200,
    negotiable: false,
    featured: true,
    packageType: "full",
    includes: ["Manuscript (.docx + .pdf)", "Cover design (.psd + .jpg)", "Series outline (Book 1 of 3)", "Glossary of terms", "Character bible"],
    formats: ["docx", "pdf", "psd"],
    description: "Book one of The Fold Trilogy. Set in 2087, a quantum physicist discovers that human consciousness can be 'folded' — compressed and transmitted across space-time. But when the first test reveals a consciousness already waiting in the fold, the discovery becomes a first-contact scenario unlike any imagined.\n\nHard SF with rigorous science backing every concept. The series outline is included, making this ideal for a publisher looking for a complete trilogy pitch. Fully edited with sensitivity reading complete.",
    excerpt: "There was someone else in the fold. Not a signal, not an echo — a mind. Patient, vast, and waiting for exactly this moment.",
    listedDate: "2026-03-01",
    coverGradient: ["#001219", "#005f73", "#0a9396"],
    coverAccent: "#94d2bd",
    tags: ["hard sci-fi", "first contact", "series", "quantum physics"],
    wordRange: "100k+"
  },
  {
    id: "rtp-004",
    title: "Lead Without a Room",
    author: "R. Holloway",
    sellerId: "seller-003",
    genre: "business",
    audience: "adult",
    wordCount: 58000,
    price: 1600,
    negotiable: false,
    featured: false,
    packageType: "full",
    includes: ["Manuscript (.docx + .pdf)", "Cover design (.ai + .jpg)", "Marketing copy (back cover, Amazon description, 5 social posts)", "Chapter-by-chapter summary"],
    formats: ["docx", "pdf", "ai", "jpg"],
    description: "A practical leadership guide for middle managers who lead high-performing teams without formal authority. Draws on 200+ interviews with team leads at Fortune 500 companies and startups. The book presents the LEVER framework — Listen, Empower, Validate, Execute, Reflect — with case studies and actionable exercises in each chapter.\n\nA business book that reads like a story, with narrative case studies opening each chapter. The author has declined traditional publishing to focus on their consulting practice, making this a rare opportunity.",
    excerpt: "Nobody gave Sarah the authority to change how her team worked. She did it anyway, one conversation at a time. Three years later, her division was the only one that didn't lose a single person in the Great Resignation.",
    listedDate: "2025-12-10",
    coverGradient: ["#0d1b2a", "#1b2a3b", "#253545"],
    coverAccent: "#C9A84C",
    tags: ["leadership", "management", "LEVER framework", "corporate"],
    wordRange: "50k-80k"
  },
  {
    id: "rtp-005",
    title: "Glass Meridian",
    author: "M. Sterling",
    sellerId: "seller-002",
    genre: "thriller",
    audience: "adult",
    wordCount: 89000,
    price: 2100,
    negotiable: true,
    featured: false,
    packageType: "manuscript",
    includes: ["Manuscript (.docx + .pdf)", "Detailed synopsis (3 pages)", "Query letter (agent-ready)"],
    formats: ["docx", "pdf"],
    description: "A psychological thriller following Elena Marsh, a forensic accountant who uncovers a money-laundering operation inside the charity she's auditing — only to realize the money trail leads back to her own missing sister's last known employer.\n\nFast-paced, dual-timeline narrative. Fully developmental-edited and proofread. Agent-ready query packet included. The book was shortlisted for a regional crime writing prize. Selling due to career change away from fiction.",
    excerpt: "Every number told a story. Elena had spent her career reading them. These numbers were lying — but the interesting question wasn't how. It was who they were protecting.",
    listedDate: "2026-01-05",
    coverGradient: ["#0f0f1a", "#1a1a2e", "#2d2d44"],
    coverAccent: "#E74C3C",
    tags: ["psychological thriller", "dual timeline", "query-ready", "female protagonist"],
    wordRange: "80k-100k"
  },
  {
    id: "rtp-006",
    title: "The Moonkin Chronicles: Pip's First Winter",
    author: "A. Vance",
    sellerId: "seller-001",
    genre: "children",
    audience: "children",
    wordCount: 24000,
    price: 950,
    negotiable: false,
    featured: false,
    packageType: "full",
    includes: ["Manuscript (.docx)", "12 full-colour illustration files (.psd + .png)", "Sketch storyboard for all spreads", "Licensing note for illustrations"],
    formats: ["docx", "png", "psd"],
    description: "A middle-grade illustrated chapter book (ages 6–9) following Pip, a small moonkin — a creature half-owl, half-fox — navigating her first winter in the enchanted Thornwood forest. The story teaches resilience and community through gentle adventure and vivid imagery.\n\nAll 12 chapter illustrations are fully completed digital watercolour paintings. The book is formatted for 128-page standard picture-chapter hybrid layout. Ideal for a publisher looking for a complete, ready-to-print package.",
    excerpt: "Pip had never seen snow before. It was cold, and wet, and entirely too white. She stuck her nose in a drift and sneezed so hard her ears flipped inside out.",
    listedDate: "2026-02-28",
    coverGradient: ["#0a1a2a", "#1a3050", "#2a4a70"],
    coverAccent: "#FF9800",
    tags: ["illustrated", "middle grade", "series potential", "complete art"],
    wordRange: "under-30k"
  },
  {
    id: "rtp-007",
    title: "Unmade Hours",
    author: "M. Sterling",
    sellerId: "seller-002",
    genre: "mystery",
    audience: "adult",
    wordCount: 71000,
    price: 1700,
    negotiable: false,
    featured: false,
    packageType: "manuscript",
    includes: ["Manuscript (.docx + .pdf)", "Synopsis (2 pages)"],
    formats: ["docx", "pdf"],
    description: "A cozy mystery set in a small Scottish coastal town, following retired clockmaker Alistair Finch who gets drawn into solving the disappearance of a local antique dealer. With a cast of eccentric locals, a labyrinthine antique shop, and clocks that seem to know too much, this is classic whodunit with modern sensibilities.\n\nSeries potential — Alistair and his community are built for recurring mysteries. Fully copyedited.",
    excerpt: "The shop had been locked from the inside. The key was on its hook. The owner was gone. These were the facts. Alistair knew facts were just the parts of a story that hadn't explained themselves yet.",
    listedDate: "2025-11-22",
    coverGradient: ["#1a1a18", "#2c2c28", "#3d3d38"],
    coverAccent: "#9E9E9E",
    tags: ["cozy mystery", "Scottish setting", "series potential", "amateur detective"],
    wordRange: "60k-80k"
  },
  {
    id: "rtp-008",
    title: "Atlas of Forgotten Futures",
    author: "J. Nakamura",
    sellerId: "seller-004",
    genre: "scifi",
    audience: "adult",
    wordCount: 67000,
    price: 1900,
    negotiable: true,
    featured: false,
    packageType: "cover",
    includes: ["Manuscript (.docx)", "Cover design (.jpg + .png)"],
    formats: ["docx", "jpg", "png"],
    description: "A speculative fiction collection of twelve interconnected stories set in the same universe, 50–500 years in the future. Each story features a different protagonist but all are linked by a mysterious atlas that passes through time and reveals 'futures that were almost chosen.'\n\nInspired by Ted Chiang's Story of Your Life and Italo Calvino's Invisible Cities. The collection has a strong editorial vision and could be published as-is or expanded.",
    excerpt: "The atlas contained maps of places that didn't exist. Or rather: places that existed, briefly, as possibility — wavefunctions that collapsed the wrong way, or the right way, depending on who you were.",
    listedDate: "2026-01-19",
    coverGradient: ["#04070d", "#091629", "#0d2040"],
    coverAccent: "#00BCD4",
    tags: ["short story collection", "interconnected", "speculative", "literary SF"],
    wordRange: "60k-80k"
  },
  {
    id: "rtp-009",
    title: "Ninety Days to Yes",
    author: "R. Holloway",
    sellerId: "seller-003",
    genre: "selfhelp",
    audience: "adult",
    wordCount: 44000,
    price: 1100,
    negotiable: false,
    featured: false,
    packageType: "full",
    includes: ["Manuscript (.docx + .pdf)", "Cover design (.jpg)", "Workbook companion (PDF)", "Email course outline (30 days)"],
    formats: ["docx", "pdf", "jpg"],
    description: "A 90-day habit-change system rooted in behavioral psychology and neuroscience. The book takes readers through a structured process of auditing their environment, building keystone habits, and designing their identity around their goals. Unlike most habit books, this one explicitly addresses failure modes and relapse.\n\nComes with a companion workbook and a 30-day email course outline for creators building a course around the book. Very complete package for a productivity publisher.",
    excerpt: "Most habit books are about what to do. This one is about who you need to become before doing it will feel natural. That's a different project — and a more honest one.",
    listedDate: "2025-12-28",
    coverGradient: ["#0d1a0a", "#1a2e15", "#253d1e"],
    coverAccent: "#4CAF50",
    tags: ["habit formation", "behavioral psychology", "workbook", "course-ready"],
    wordRange: "30k-50k"
  },
  {
    id: "rtp-010",
    title: "Dark Between Stars",
    author: "A. Vance",
    sellerId: "seller-001",
    genre: "fantasy",
    audience: "adult",
    wordCount: 118000,
    price: 3600,
    negotiable: false,
    featured: false,
    packageType: "full",
    includes: ["Manuscript (.docx + .pdf)", "Cover design (.psd + .jpg)", "World atlas (illustrated, 12 maps)", "Magic system document (20pp)", "Character relationship chart", "Full trilogy outline"],
    formats: ["docx", "pdf", "psd"],
    description: "An epic fantasy set in a world where the night sky is a living map, and those who can read it hold absolute political power. When the stars begin to go dark — extinguished one by one over decades — the empire's star-readers must choose between protecting their power or admitting the truth.\n\nBook 1 of a completed trilogy. All three manuscripts exist in draft form. This listing includes the fully polished Book 1 plus the complete world-building and series bible. One of the most complete packages listed on ReadyToPublish.",
    excerpt: "The last star in the Raven's Wing went dark on a Tuesday. The empire's astrologers declared it a good omen. Nobody believed them — not even the astrologers.",
    listedDate: "2026-03-10",
    coverGradient: ["#010108", "#08081f", "#100f30"],
    coverAccent: "#9C27B0",
    tags: ["epic fantasy", "completed trilogy", "worldbuilding", "political fantasy"],
    wordRange: "100k+"
  },
  {
    id: "rtp-011",
    title: "When the Body Keeps the Score (A Memoir)",
    author: "R. Holloway",
    sellerId: "seller-003",
    genre: "nonfiction",
    audience: "adult",
    wordCount: 76000,
    price: 1950,
    negotiable: true,
    featured: false,
    packageType: "manuscript",
    includes: ["Manuscript (.docx + .pdf)", "Proposal package (book proposal, sample chapters, author bio, comp titles)", "Agent query letter"],
    formats: ["docx", "pdf"],
    description: "A literary memoir about recovering from chronic illness and the medical system's failures. Weaves personal narrative with medical research, told with unflinching honesty and dark humor. The writing has been compared to Mary Karr and Maggie Nelson.\n\nComes with a complete book proposal package suitable for both agents and small presses. The author chose not to pursue traditional publication due to timeline constraints. Rare opportunity for a memoir with strong commercial comp titles.",
    excerpt: "Doctors talk about the body like it's a malfunctioning machine. I spent two years learning that my body wasn't broken — it was speaking a language nobody had bothered to translate.",
    listedDate: "2026-02-07",
    coverGradient: ["#1a0f0a", "#2e1a10", "#3d2318"],
    coverAccent: "#FF7043",
    tags: ["memoir", "chronic illness", "literary", "proposal included"],
    wordRange: "60k-80k"
  },
  {
    id: "rtp-012",
    title: "The Duplass Convergence",
    author: "C. Oduya",
    sellerId: "seller-005",
    genre: "thriller",
    audience: "adult",
    wordCount: 85500,
    price: 2200,
    negotiable: false,
    featured: false,
    packageType: "manuscript",
    includes: ["Manuscript (.docx + .pdf)", "Synopsis (2pp)", "First 50 pages formatted for submission"],
    formats: ["docx", "pdf"],
    description: "A high-concept thriller following a forensic psychologist brought in to profile a serial killer — only to realize the killer's pattern is recreating the crimes from a novel that was never published. Someone had access to the manuscript. And they're following it chapter by chapter.\n\nFast-paced, high-concept thriller with a compelling central hook. Fully developmental edited. The book is actively being queried by the author's agent but the author is willing to sell the project outright to a publisher who wants to acquire directly.",
    excerpt: "Page forty-two. She'd read it three times before she understood what she was looking at. The manuscript described this crime scene in detail. It was written six years ago. The body was found this morning.",
    listedDate: "2026-03-15",
    coverGradient: ["#0f0a0a", "#1f1010", "#2e1515"],
    coverAccent: "#E53935",
    tags: ["high concept", "serial killer", "meta-thriller", "actively queried"],
    wordRange: "80k-100k"
  }
];

export const packageTypes = [
  { id: "manuscript", label: "Manuscript Only", description: "Text files only (.docx, .pdf)" },
  { id: "cover",      label: "Manuscript + Cover", description: "Text files plus cover design" },
  { id: "full",       label: "Full Package", description: "Manuscript, cover, and extras" }
];

export const wordRanges = [
  { id: "under-30k", label: "Under 30k words" },
  { id: "30k-50k",   label: "30k – 50k words" },
  { id: "50k-80k",   label: "50k – 80k words" },
  { id: "80k-100k",  label: "80k – 100k words" },
  { id: "100k+",     label: "100k+ words" }
];

export const audiences = [
  { id: "adult",        label: "Adult" },
  { id: "ya",           label: "Young Adult" },
  { id: "children",     label: "Children's" },
  { id: "middle-grade", label: "Middle Grade" }
];

export const testimonials = [
  {
    name: "Petra Klaas",
    role: "Publisher, Nordlight Press",
    initials: "PK",
    color: "#6B4EFF",
    rating: 5,
    text: "We acquired two manuscripts through ReadyToPublish last quarter. Both were polished, immediately ready for production. The due diligence process saved us months."
  },
  {
    name: "T. Okonkwo",
    role: "Fiction Author",
    initials: "TO",
    color: "#E91E8C",
    rating: 5,
    text: "I sold a project I'd been sitting on for three years within ten days of listing. The buyer was a hybrid publisher who published it six months later. Incredible platform."
  },
  {
    name: "David Schreiber",
    role: "Literary Agent, Berg & Associates",
    initials: "DS",
    color: "#0097A7",
    rating: 4,
    text: "A useful discovery tool for identifying acquisition-ready manuscripts. Several of my clients have found excellent secondary rights buyers here."
  }
];
